RAND: 4567

# original data dir
DATA_DIR: "../data/raw"

# data
train_data: "../data/raw/train.csv"  
test_data: "../data/raw/test.csv"

N_FOLDS: 10

MODEL:
  model_name: "lr-rel_fts"
  save_models: True
  save_model_to: "../models"
  desc: 'lr on rel fts.'


# for wandb
project: "renew-machinehack"
