RAND: 4567

# original data dir
DATA_DIR: "../data/raw"

# data
train_data: "../data/train_T1.csv"  
test_data: "../data/test_T1.csv"

N_FOLDS: 10

MODEL:
  model_name: "lr_T1"
  save_models: True
  save_model_to: "../models"
  desc: 'lr on time based fts.'


# for wandb
project: "renew-machinehack"
