RAND: 4567

# original data
DATA_DIR: "../data/raw"

# preprocessed data
train_data: "../data/raw/train.csv"
test_data: "../data/raw/test.csv"

N_FOLDS: 10

MODEL:
  model_name: "cb_5k_pca_pf"
  save_models: True
  save_model_to: "../models"
  desc: 'cb5k with 10pca, 2nd deg pf features'


# for wandb
project: "renew-machinehack"
