RAND: 4567

# original data
DATA_DIR: "../data/raw"

# preprocessed data
train_data: "../data/raw/train.csv"
test_data: "../data/raw/test.csv"

N_FOLDS: 10

MODEL:
  model_name: "lr_pf2"
  save_models: True
  save_model_to: "../models"
  desc: 'simple lr  deg2_pf'


# for wandb
project: "renew-machinehack"
